version: 0.2

env:
  variables:
    LAYER_NAME: "cbor-mysql-layer"
    ARTIFACT_BUCKET: "cbor-artifact-bckt"

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.9
    commands:
      - echo "➡ Installing python dependencies into layer structure"
      - mkdir -p python
      - pip install -r cbor/requirements.txt -t python/

      - echo "➡ Downloading MySQL JDBC driver"
      - curl -L -o mysql-connector-j-8.3.0.zip https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-8.3.0.zip
      - unzip mysql-connector-j-8.3.0.zip
      - cp mysql-connector-j-8.3.0/mysql-connector-j-8.3.0.jar python/

      - echo "➡ Searching & copying JVM (libjvm.so)"
      - mkdir -p python/lib/server
      - bash -c 'JVM_PATH=$(find /usr/lib/jvm -name "libjvm.so" | head -n 1); echo "Found JVM at: $JVM_PATH"; cp "$JVM_PATH" python/lib/server/'

  build:
    commands:
      - echo "➡ Zipping lambda layer"
      - zip -r layer.zip python/

      - echo "➡ Packaging CloudFormation (cbor_components.yaml)"
      - aws cloudformation package \
          --template-file cbor/cbor_components.yaml \
          --s3-bucket $ARTIFACT_BUCKET \
          --output-template-file packaged_cbor_components.yml

      - echo "⭐ Layer & packaged template ready"

artifacts:
  base-directory: .
  files:
    - layer.zip
    - packaged_cbor_components.yml
    - cbor/dev.json
  discard-paths: yes
