AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for CBOR (MySQL-based)

Parameters:
  NotificationEmail:
    Description: Email address to notify if there are any errors in CBOR
    Type: String
    Default: kuthariag@gmail.com

  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, stage, prod]

  Application:
    Type: String
    Default: customer-book-of-records-api

  LambdaRole:
    Type: String
    Default: CBORLambdaExecutionRole

  LambdapythonRuntime:
    Type: String
    Default: python3.9

  LambdaMemorySize:
    Type: Number
    Default: 256

  LambdaTimeout:
    Type: Number
    Default: 300

  SecurityContact:
    Type: String
    Default: kuthariag@gmail.com

  CborpythonLambdaHandler:
    Type: String
    Default: customer-book-of-records.lambda_handler

  MySQLHost:
    Type: String
    Default: localhost

  MySQLPort:
    Type: String
    Default: 3306

  MySQLUser:
    Type: String
    Default: root

  MySQLPassword:
    Type: String
    Default: aman@K123

  MySQLDatabase:
    Type: String
    Default: company_db

Resources:

  PythonLibs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref Application
      CompatibleRuntimes:
        - python3.9
      ContentUri: layer.zip
 

  CborSecrets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: secrets_manager/cbor_secrets.yaml
      Parameters:
        Environment: !Ref Environment
        Application: !Ref Application
        LambdaRole: !Ref LambdaRole
        LambdapythonRuntime: !Ref LambdapythonRuntime
        LambdaMemorySize: !Ref LambdaMemorySize
        LambdaTimeout: !Ref LambdaTimeout
        SecurityContact: !Ref SecurityContact
        NotificationEmail: !Ref NotificationEmail
        CborpythonLambdaHandler: !Ref CborpythonLambdaHandler
        MySQLHost: !Ref MySQLHost
        MySQLPort: !Ref MySQLPort
        MySQLUser: !Ref MySQLUser
        MySQLPassword: !Ref MySQLPassword
        MySQLDatabase: !Ref MySQLDatabase

  cborLambdas:
    Type: AWS::CloudFormation::Stack
    DependsOn: CborSecrets
    Properties:
      TemplateURL: lambdas/customer_book_of_records_lambda.yaml
      Parameters:
        Environment: !Ref Environment
        Application: !Ref Application
        LambdaRole: !Ref LambdaRole
        LambdapythonRuntime: !Ref LambdapythonRuntime
        LambdaMemorySize: !Ref LambdaMemorySize
        LambdaTimeout: !Ref LambdaTimeout
        SecurityContact: !Ref SecurityContact
        NotificationEmail: !Ref NotificationEmail
        CborpythonLambdaHandler: !Ref CborpythonLambdaHandler
        MySQLDbCredentialsARN: !GetAtt CborSecrets.Outputs.MySQLDbCredentialsARN
