Parameters:
  Environment:
    Type: String
  Application:
    Type: String
  LambdaRole:
    Type: String
  LambdapythonRuntime:
    Type: String
  LambdaMemorySize:
    Type: String
  LambdaTimeout:
    Type: String
  SecurityContact:
    Type: String
  NotificationEmail:
    Type: String
    Description: Notification email address
  CborpythonLambdaHandler:
    Type: String
  MySQLHost:
    Type: String
  MySQLPort:
    Type: String
  MySQLUser:
    Type: String
  MySQLPassword:
    Type: String
  MySQLDatabase:
    Type: String
 
Resources:
  MySQLDatabaseCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: MySQL database credentials for the CBOR Lambda.
      Name: !Join [ "-", [ !Ref Environment, !Ref Application, "mysql-database-credentials" ] ]
      SecretString: !Sub |
        {
          "host": "${MySQLHost}",
          "port": "${MySQLPort}",
          "user": "${MySQLUser}",
          "password": "${MySQLPassword}",
          "database": "${MySQLDatabase}"
        }
      Tags:
        - Key: Name
          Value: !Join [ "-", [ !Ref Environment, !Ref Application, "mysql-database-credentials" ] ]
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref Application
        - Key: SecurityContact
          Value: !Ref SecurityContact
 
Outputs:
  MySQLDbCredentialsARN:
    Description: The ARN for the MySQL database credentials stored in Secrets Manager
    Value: !Ref MySQLDatabaseCredentials
    Export:
      Name: !Join [ "-", [ !Ref Environment, !Ref Application, "mysql-database-credentials-arn" ] ]
 
 